
spring.application.name=backend

# PostgreSQL connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true